INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('18-1=KLRUDT', 'fifo', 25, 'rerunsAllowed', 1, 0, 0, 'Father Brown', 'all', 1, 7);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('18-1=KLRUDT', 'fifo', 2, 'rerunsAllowed', 2, 0, 0, 'BBC World News', 'all', 1, 2011);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('24-1=KVUEDT', 'fifo', 2, 'rerunsAllowed', 3, 0, 0, 'KVUE News Daybreak at 4:30AM', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('24-1=KVUEDT', 'fifo', 10, 'rerunsAllowed', 4, 0, 0, 'KVUE News Daybreak', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('36-1=KXANDT', 'fifo', 2, 'rerunsAllowed', 6, 0, 0, 'KXAN News Today', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('42-1=KEYEDT', 'fifo', 2, 'rerunsAllowed', 7, 0, 0, 'CBS Austin Morning News', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('36-1=KXANDT', 'fifo', 25, 'firstRunOnly', 8, 0, 1, 'The Blacklist', 'linear', 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('42-1=KEYEDT', 'forever', 10, 'everyEpisode', 9, 0, 60, 'Elementary', 'linear', 1, 6);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('42-1=KEYEDT', 'fifo', 10, 'firstRunOnly', 10, 0, 1, 'Mom', 'linear', 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('24-1=KVUEDT', 'fifo', 10, 'firstRunOnly', 11, 0, 1, 'Marvel''s Agents of S.H.I.E.L.D.', 'linear', 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('42-1=KEYEDT', 'fifo', 5, 'firstRunOnly', 12, 0, 30, 'The Late Show With Stephen Colbert', 'linear', 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('54-1=KNVADT', 'fifo', 10, 'firstRunOnly', 13, 0, 1, 'Supernatural', 'linear', 1, 12);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'forever', 0, 'firstRunOnly', 14, 0, 5, 'Archer', 'all', 1, 8);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('54-1=KNVADT', 'fifo', 10, 'rerunsAllowed', 15, 0, 1, 'iZombie', 'linear', 1, 4);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('42-1=KEYEDT', 'fifo', 2, 'rerunsAllowed', 16, 0, 30, 'Face the Nation', 'linear', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('24-1=KVUEDT', 'fifo', 2, 'rerunsAllowed', 17, 0, 3, 'This Week With George Stephanopoulos', 'linear', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('All Channels', 'fifo', 2, 'rerunsAllowed', 18, 0, 3, 'Meet the Press', 'linear', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('18-3=KLRUDT3', 'fifo', 0, 'rerunsAllowed', 19, 0, 3, 'Death in Paradise', 'all', 1, 9);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('7-1=KTBCDT', 'fifo', 25, 'rerunsAllowed', 20, 0, 1, 'The Gifted', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('42-1=KEYEDT', 'fifo', 25, 'firstRunOnly', 21, 0, 1, 'Young Sheldon', 'all', 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('36-1=KXANDT', 'fifo', 25, 'firstRunOnly', 22, 0, 1, 'Blindspot', 'linear', 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('42-1=KEYEDT', 'fifo', 2, 'firstRunOnly', 23, 0, 1, '60 Minutes', 'all', 1, 50);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 2, 'firstRunOnly', 24, 0, 1, 'The Rookie', 'all', 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('18-3=KLRUDT3', 'fifo', 25, 'rerunsAllowed', 25, 0, 1, 'History Detectives', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('24-1=KVUEDT', 'fifo', 2, 'rerunsAllowed', 26, 0, 1, 'Whiskey Cavalier', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 27, 0, 0, 'Blood & Treasure', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 28, 0, 0, 'Shakespeare and Hathaway: Private Investigators', 'all', 1, 3);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 29, 0, 0, 'The Rook', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'firstRunOnly', 31, 0, 1, 'The Neighborhood', 'all', 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('18-1=KLRUDT', 'fifo', 10, 'firstRunOnly', 32, 0, 1, 'NOVA', 'linear', 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('24-1=KVUEDT', 'fifo', 25, 'firstRunOnly', 33, 0, 1, 'Designated Survivor', 'linear', 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('WL', 'fifo', 0, 'rerunsAllowed', 34, 0, 0, 'Doctor Who', null, 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('54-1=KNVADT', 'fifo', 25, 'rerunsAllowed', 35, 0, 0, 'Roswell, New Mexico', 'all', 1, 2);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('54-1=KNVADT', 'fifo', 25, 'rerunsAllowed', 36, 0, 0, 'Stargirl', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('All Channels', 'fifo', 25, 'rerunsAllowed', 37, 0, 0, 'Will & Grace', 'linear', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('24-1=KVUEDT', 'fifo', 2, 'rerunsAllowed', 38, 0, 0, 'Good Morning America', 'all', 1, 2020);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('onDemand', 'fifo', 5, 'rerunsAllowed', 39, 0, 0, 'NOS4A2', 'onDemand', 1, 2);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('24-1=KVUEDT', 'fifo', 5, 'rerunsAllowed', 40, 0, 30, 'ABC News: Your Voice Your Vote 2020', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('WL', 'fifo', 5, 'rerunsAllowed', 41, 0, 0, 'DEBATE', null, 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('36-1=KXANDT', 'fifo', 5, 'rerunsAllowed', 42, 0, 0, 'State of Texas', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 5, 'rerunsAllowed', 43, 0, 0, 'CBS Sunday Morning', 'all', 1, 40);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('All Channels', 'fifo', 10, 'rerunsAllowed', 42, 0, 10, 'Last Week Tonight With John Oliver', 'linear', 1, 5);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('All Channels', 'fifo', 10, 'firstRunOnly', 43, 0, 1, 'Fear the Walking Dead', 'linear', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('All Channels', 'fifo', 2, 'rerunsAllowed', 44, 0, 1, 'Real Time With Bill Maher', 'linear', 1, 16);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('All Channels', 'fifo', 10, 'rerunsAllowed', 45, 0, 5, 'Vice', 'linear', 1, 6);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('All Channels', 'fifo', 10, 'firstRunOnly', 46, 0, 3, 'Silicon Valley', 'linear', 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('All Channels', 'fifo', 0, 'rerunsAllowed', 47, 0, 3, 'Westworld', 'linear', 1, 3);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('1209=KEYEDT', 'fifo', 1, 'rerunsAllowed', 48, 0, 30, 'Face the Nation', 'linear', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('1200=KVUEDT', 'fifo', 1, 'rerunsAllowed', 49, 0, 3, 'This Week With George Stephanopoulos', 'linear', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('All Channels', 'fifo', 1, 'rerunsAllowed', 50, 0, 3, 'Meet the Press', 'linear', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('All Channels', 'fifo', 2, 'firstRunOnly', 51, 0, 3, 'GMT', 'linear', 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('113=COMEDYHD-E', 'fifo', 10, 'firstRunOnly', 52, 0, 3, 'The Jim Jefferies Show', 'linear', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('1268=KLRUDT3', 'fifo', 0, 'rerunsAllowed', 53, 0, 3, 'Death in Paradise', 'all', 1, 8);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('105=AMCHD-E', 'fifo', 10, 'firstRunOnly', 54, 0, 3, 'Talking Preacher', 'linear', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('1209=KEYEDT', 'fifo', 25, 'rerunsAllowed', 55, 0, 1, 'Star Trek: Discovery', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('1209=KEYEDT', 'fifo', 5, 'firstRunOnly', 56, 0, 1, 'Young Sheldon', 'all', 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 57, 0, 1, 'I Love You, America with Sarah Silverman', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('105=AMCHD-E', 'fifo', 10, 'rerunsAllowed', 58, 0, 3, 'Talking With Chris Hardwick', 'linear', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'firstRunOnly', 59, 0, 1, 'Santa Clarita Diet', 'all', 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('1203=KXANDT', 'fifo', 25, 'firstRunOnly', 60, 0, 1, 'Blindspot', 'linear', 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('105=AMCHD-E', 'fifo', 25, 'firstRunOnly', 61, 0, 1, 'Robert Kirkman''s Secret History of Comics', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('111=SYFYHD-E', 'fifo', 25, 'rerunsAllowed', 62, 0, 1, 'Happy!', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('187=OVATIONHD', 'fifo', 0, 'rerunsAllowed', 63, 0, 1, 'The Artful Detective', 'all', 1, 12);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('110=BBCAMHD-E', 'fifo', 25, 'firstRunOnly', 64, 0, 1, 'Dirk Gently''s Holistic Detective Agency', 'all', 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('104=TBSHD-E', 'fifo', 25, 'rerunsAllowed', 65, 0, 5, 'The Alienist: Angel of Darkness', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('All Channels', 'fifo', 10, 'firstRunOnly', 66, 0, 3, 'The Leftovers', 'linear', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('113=COMEDYHD-E', 'fifo', 25, 'firstRunOnly', 67, 0, 10, 'This Is Not Happening', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 5, 'rerunsAllowed', 68, 0, 5, 'Brockmire', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('108=FXHD-E', 'fifo', 25, 'firstRunOnly', 69, 0, 1, 'Legion', 'all', 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('110=BBCAMHD-E', 'forever', 0, 'rerunsAllowed', 70, 0, 1, 'Killing Eve', 'all', 1, 2);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('1209=KEYEDT', 'fifo', 2, 'firstRunOnly', 71, 0, 1, '60 Minutes', 'all', 1, 50);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 72, 0, 1, 'Outlander', 'all', 1, 4);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 2, 'firstRunOnly', 73, 0, 1, 'Wyatt Cenac''s Problem Areas', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'firstRunOnly', 74, 0, 1, 'Drain the Oceans', 'all', 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 75, 0, 1, 'Marvel''s Cloak and Dagger', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('105=AMCHD-E', 'fifo', 25, 'rerunsAllowed', 76, 0, 1, 'Unapologetic With Aisha Tyler', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'firstRunOnly', 77, 0, 1, 'The Break With Michelle Wolf', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'firstRunOnly', 78, 0, 1, 'Lodge 49', 'all', 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 2, 'firstRunOnly', 79, 0, 1, 'The Rookie', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'firstRunOnly', 80, 0, 1, 'The Neighborhood', 'all', 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 81, 0, 1, 'Counterpart', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('WL', 'fifo', 0, 'rerunsAllowed', 82, 0, 0, 'THE RIFT', null, 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 83, 0, 1, 'Mars', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('All Channels', 'fifo', 2, 'firstRunOnly', 84, 0, 1, 'Last Man Standing', 'linear', 1, 7);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('WL', 'fifo', 0, 'rerunsAllowed', 85, 0, 0, 'Chris Hardwick', null, 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('1206=KTBCDT', 'fifo', 2, 'firstRunOnly', 86, 0, 1, 'The Passage', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('1268=KLRUDT3', 'fifo', 25, 'rerunsAllowed', 87, 0, 1, 'History Detectives', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 88, 0, 1, 'Roswell, New Mexico', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 89, 0, 1, 'Shameless', 'all', 1, 8);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'firstRunOnly', 90, 0, 1, 'Patriot Act with Hasan Minhaj', 'all', 1, 2);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 91, 0, 1, 'Good Omens', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('1200=KVUEDT', 'fifo', 2, 'rerunsAllowed', 92, 0, 1, 'Whiskey Cavalier', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 2, 'firstRunOnly', 93, 0, 1, 'Barry', 'all', 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 94, 0, 1, 'Alien News Desk', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 95, 0, 1, 'SMILF', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('All Channels', 'fifo', 10, 'rerunsAllowed', 96, 0, 3, 'Fargo', 'linear', 1, 3);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 97, 0, 0, 'A Discovery of Witches', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 98, 0, 0, 'Blood & Treasure', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 99, 0, 0, 'The Hot Zone', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 100, 0, 0, 'Axios', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 101, 0, 0, 'Luther', 'all', 1, 5);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 102, 0, 0, 'NOS4A2', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 103, 0, 0, 'Gentleman Jack', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 104, 0, 0, 'Shakespeare and Hathaway: Private Investigators', 'all', 1, 3);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 0, 'firstRunOnly', 105, 0, 0, 'Divorce', 'all', 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 106, 0, 0, 'The Rook', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 107, 0, 0, 'Absentia', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 5, 'rerunsAllowed', 108, 0, 5, 'Lights Out with David Spade', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('WL', 'forever', 25, 'rerunsAllowed', 109, 0, 0, 'Fantastic Beasts: The Crimes of Grindelwald, Movies: Fantasy', null, 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('WL', 'fifo', 0, 'rerunsAllowed', 110, 0, 0, 'Joss Whedon', null, 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('WL', 'fifo', 0, 'rerunsAllowed', 111, 0, 0, 'Jodie Comer', null, 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('WL', 'fifo', 25, 'rerunsAllowed', 112, 0, 0, 'Sonya Walger', null, 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('WL', 'fifo', 0, 'rerunsAllowed', 113, 0, 0, 'Samara Weaving', null, 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('WL', 'fifo', 0, 'rerunsAllowed', 114, 0, 0, 'Samantha Womack', null, 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('WL', 'fifo', 0, 'rerunsAllowed', 115, 0, 0, 'Christine Nguyen', null, 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('WL', 'fifo', 25, 'rerunsAllowed', 116, 0, 0, 'DEBATE', null, 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 5, 'firstRunOnly', 117, 0, 0, 'Our Cartoon President', 'all', 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('1221=KLRUDT', 'fifo', 25, 'rerunsAllowed', 118, 0, 0, 'Father Brown', 'all', 1, 7);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('113=COMEDYHD-E', 'fifo', 5, 'firstRunOnly', 119, 0, 0, 'South Park', 'all', 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('WL', 'forever', 25, 'rerunsAllowed', 120, 0, 0, 'Gemini Man, Movies: Science Fiction', null, 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('WL', 'forever', 25, 'rerunsAllowed', 121, 0, 0, 'The Dead Don''t Die, Movies: Comedy', null, 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('WL', 'forever', 25, 'rerunsAllowed', 122, 0, 0, 'The Current War, Movies: Drama', null, 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 123, 0, 0, 'Bless the Harts', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('113=COMEDYHD-E', 'fifo', 10, 'rerunsAllowed', 124, 0, 0, 'Good Talk with Anthony Jeselnik', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 125, 0, 0, 'Mary Kills People', 'all', 1, 3);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 126, 0, 0, 'Abby''s', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('1209=KEYEDT', 'fifo', 25, 'rerunsAllowed', 127, 0, 0, 'Evil', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('1209=KEYEDT', 'fifo', 5, 'rerunsAllowed', 128, 0, 0, 'Bob (Hearts) Abishola', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 129, 0, 0, 'Stumptown', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 5, 'rerunsAllowed', 130, 0, 0, 'Carol''s Second Act', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('1203=KXANDT', 'fifo', 25, 'rerunsAllowed', 131, 0, 0, 'Perfect Harmony', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('1203=KXANDT', 'fifo', 25, 'everyEpisode', 132, 0, 0, 'Sunnyside', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('1209=KEYEDT', 'fifo', 5, 'rerunsAllowed', 133, 0, 0, 'The Unicorn', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'firstRunOnly', 134, 0, 0, 'Pennyworth', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 5, 'firstRunOnly', 135, 0, 0, 'Batwoman', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('1212=KNVADT', 'fifo', 25, 'rerunsAllowed', 136, 0, 0, 'Stargirl', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 5, 'rerunsAllowed', 137, 0, 0, 'Nancy Drew', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 138, 0, 0, 'His Dark Materials', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 139, 0, 0, 'Watchmen', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 5, 'rerunsAllowed', 140, 0, 0, 'Impeachment Inquiry, House Hearings', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('WL', 'fifo', 25, 'rerunsAllowed', 141, 0, 0, '2018', null, 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('WL', 'fifo', 25, 'rerunsAllowed', 142, 0, 0, 'Watchmen - The Ultimate Cut, Movies: Action Adventure', null, 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 25, 'rerunsAllowed', 143, 0, 0, 'Avenue 5', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('1206=KTBCDT', 'fifo', 5, 'rerunsAllowed', 144, 0, 0, 'Outmatched', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'forever', 25, 'rerunsAllowed', 145, 0, 5, 'Dispatches From Elsewhere', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('WL', 'fifo', 25, 'rerunsAllowed', 146, 0, 0, 'YEAR OF THE RABBIT', null, 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('111=SYFYHD-E', 'fifo', 25, 'rerunsAllowed', 147, 0, 0, 'Vagrant Queen', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('WL', 'fifo', 25, 'rerunsAllowed', 148, 0, 0, 'YEAR OF THE RABBIT', null, 1, 0);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('511=HBOHD-E', 'fifo', 25, 'rerunsAllowed', 149, 0, 0, 'Run', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('1200=KVUEDT', 'fifo', 1, 'rerunsAllowed', 150, 0, 0, 'Good Morning America', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('165=TRAVELHD-E', 'fifo', 25, 'rerunsAllowed', 151, 0, 0, 'Paranormal Caught on Camera', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('1209=KEYEDT', 'fifo', 25, 'rerunsAllowed', 152, 0, 0, 'The Henry Ford''s Innovation Nation', 'all', 1, 6);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('107=HISTHD-E', 'fifo', 25, 'rerunsAllowed', 153, 0, 0, 'Ultimate Rides', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('1200=KVUEDT', 'fifo', 5, 'rerunsAllowed', 154, 0, 0, 'ABC World News Tonight With David Muir', 'all', 1, 2020);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES (null, 'fifo', 5, 'rerunsAllowed', 155, 0, 0, 'Dead Pixels', 'all', 1, 1);
INSERT INTO RoamioSp (Channel, Keep, Num, Record, Priority, Start, End, Show, Include, Userid, Season) VALUES ('WL', 'fifo', 5, 'rerunsAllowed', 156, 0, 0, 'DEBATE', null, 1, 0);
