CREATE TABLE ShowsUser(id INTEGER NOT NULL primary key autoincrement,
Imdb	VARCHAR(2),
JustWatchLink	VARCHAR(75),
LastWatched	VARCHAR(10) NOT NULL,
ImdbLink	VARCHAR(63),
InShowRssAsLink	VARCHAR(32),
Diff	VARCHAR(3),
CommentLink	VARCHAR(228),
Userid	INTEGER,
InRokuFeed	VARCHAR(1),
BestExperience	VARCHAR(17),
ShowsId	INTEGER,
InShowRssAs	VARCHAR(47),
JustWatch	VARCHAR(2),
InTablo	VARCHAR(1),
Comment	VARCHAR(181),
BestExperienceLink	VARCHAR(306),
Ota	VARCHAR(1),    CONSTRAINT FK_ShowsUser_ShowsId FOREIGN KEY (ShowsId)    REFERENCES Shows(id),    CONSTRAINT FK_ShowsUser_Userid FOREIGN KEY (Userid)    REFERENCES Account(id));
